application:
  port: 8000
  host: 0.0.0.0
  api_key: "e4125dd1-3d3e-43a1-bc9c-dc0ba12ad4b5"
  templates: "templates/**/*"
database:
  type:
  database_path: sqlite:database.db
  create_if_missing: true
